name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: beta
          components: clippy
      - name: Run tests with cucumber
        run: cargo test -p template-state --test template-state-test
      - name: Run clippy
        run: cargo clippy -- -D clippy::expect_used -D clippy::panic  -D clippy::unwrap_used